### ISSUE TITLE
How to download files.

### ISSUE THREAD

**Issue by xianzhe18** [polidog/php-chatwork-api#7]
Thank you for this awesome package.

I want to get files downloaded, so I tried several ways.
But I couldn't get download link.

`https://api.chatwork.com/v2/rooms/{room_id}/files/{file_id}?create_download_url=1`

According to API document, in order to download file, download link must be created first.
But I can't see `create_download_url` key in this package.

Please let me know if I miss something.

Best Regards

Xianzhe

**Comment by polidog** [comment]
@xianzhe18 

Sorry , this library not support `create_download_url `.
I tried create Pull request #8.

What do you think #8?
